draw_text(10, 10, "custx: " + string(global.custx));
draw_text(10, 25, "custy: " + string(global.custy));
draw_text(10, 40, "direction: " + string(dir));
draw_text(10, 55, "div turn: " + string(dir div turnsize));
draw_text(10, 70, "forward: " + string(forward));
draw_text(10, 85, "strafe: " + string(strafe));
draw_text(10, 100, "hsp: " + string(hsp));
draw_text(10, 115, "vsp: " + string(vsp));
draw_text(10, 130, "run: " + string(run));
draw_text(10, 145, "root: " + string(rooted));
draw_text(10, 160, "chem: " + string(chemicalactive));
draw_text(10, 175, "see: " + string(perceiving));
